kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: $clusterName

# Registry Local
#containerdConfigPatches:
#- |
#  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
#    endpoint = ["http://kind-registry:5000"]  

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.default.svc.cluster.local:5000"]
    endpoint = ["http://registry.default.svc.cluster.local:5000"]

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32222
    hostPort: 32222
    protocol: TCP

