kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: $clusterName

# Registry Local
containerdConfigPatches:
- |
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."my-registry:5000"]
    endpoint = ["http://my-registry:5000"]  

  [plugins."io.containerd.grpc.v1.cri".registry.configs."my-registry:5000".tls]
    insecure_skip_verify = true
    plain_http = true

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32222
    hostPort: 32222
    protocol: TCP

