apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private-subnet-pool
  namespace: metallb-system
spec:
  addresses:
  - $cidr_short.240-$cidr_short.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: private-subnet-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - private-subnet-pool
