apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: $clusterName
servers: 1
agents: 0 
kubeAPI:
  host: "127.0.0.1"
  hostIP: "127.0.0.1"
  hostPort: "6443"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  
